spring:
    application:
            name: Config-dev-services


# Eureka Client Configuration
eureka:
  instance:
    prefer-ip-address: true
    client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
        default-zone: http://localhost:8761/eureka/
         fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
 

